name: Trigger auto deployment for covid-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ start ]
 
  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.COVIDAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: cloudbuilderlive.azurecr.io
          registryUsername: ${{ secrets.COVIDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COVIDAPI_REGISTRY_PASSWORD }}
          containerAppName: covid-api
          resourceGroup: AzureTest
          imageToBuild: cloudbuilderlive.azurecr.io/covid-api:${{ github.sha }}
          
            

     

